### ISSUE TITLE
running bnspatial in R.4

### ISSUE THREAD

**Issue by miriamglendell** [dariomasante/bnspatial#10]
Hi Dario, I updated my version of R and all the dependencies that are running with bnspatial. I had a perfectly working network in the previous version of R3.6 but now I get this message when running the model:

Attaching package: �gRbase�

The following objects are masked from �package:bnlearn�:

    ancestors, children, parents

no loop for break/next, jumping to top level

Could you please help me with some explanation and how to fix this problem? 

Many thanks

Miriam

**Comment by dariomasante** [comment]
Hi Miriam, you should provide minimal code to reproduce the error. 
However it does not seem to be related to bnspatial, rather to the fact that you have bnlearn package loaded and/or some of your variables names are conflicting with some bnlearn function. Try to clean up you working environment and try again.

**Comment by miriamglendell** [comment]
Thanks, I got it sorted, apologies for a silly question.
