### ISSUE TITLE
Feature request - implement utility nodes

### ISSUE THREAD

**Issue by dariomasante** [dariomasante/bnspatial#2]
Currently any utility node generates an error when reading and compiling the network. Need to remove it beforehand and calculate externally

**Comment by danivapp** [comment]
Is there an example how to calculate utility nodes externally?

**Comment by dariomasante** [comment]
Try [this](https://www.google.com/search?q=influence+diagrams+utility+calculate) or [this](https://www.google.com/search?q=decision+net+utility+calculate).
Briefly, the expected utility is the product of the utility of an event and the probability of that event. So you could write a function in R to do that (please let me know of you do that). 
There is another trick though, which probably won't work in all circumstances: by normalizing between zero an one all possible utility outcomes and using those as probabilities in a standard node, you can get the expected utility (by understanding how your BN works you should be able to find out whether this is a viable solution for your case or not).
