### ISSUE TITLE
import BBN into R without spatial data

### ISSUE THREAD

**Issue by hippieschneckeontour** [dariomasante/bnspatial#8]
Hey, it's possible to import and load a bayesian network into R without spatial data? I have a huge and complex BN. I tried the bnspatial package, but I actually don't have spatial information. So I have problems by creating the (lookup-) text file (special classBoundaries) and plot the output map. I just wanna know if the BN with the nodes and node states is really inside. Somebody maybe have a tip or a few links for me, where I can find a solution? Couldn't find informations about importing BNs without spatial data. Thanks!

P.S. Sorry for my bad English. :D

**Comment by dariomasante** [comment]
You may use the function loadNetwork, it just loads the BBN (note that the bnspatial function wraps a few other functions that are all available individually).
BUT I strongly suggest to check out the gRain and bnlearn packages, they seem more suited for your needs if you don't need to work with spatial data.

PS. if you have no spatial data at all but still want to make maps, you just cannot do that having the BBN only, it makes no sense.
